### ISSUE TITLE
Add me 

### ISSUE THREAD

**Issue by Saurabh1426** [PHP-DC/support#10]
Please invite me to the GitHub Community Organization. 

- #### Name: Saurabh Vinod Mhatre

- #### Discord Username(if exists):Gaming With Saurya

- #### Additional Context: Wanna know more about github

**Comment by cmulay** [comment]
@Saurabh1426  Please fill out the information that is required and mandatory in order to join the [organization](https://github.com/PHP-DC)

**Comment by Davekibh** [comment]
Cool!

**Comment by cmulay** [comment]
### Welcome to the community 🎉
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/PHP-DC/people
