### ISSUE TITLE
Request To Join PHP-DC

### ISSUE THREAD

**Issue by ypratham** [PHP-DC/support#2]
Please invite me to the GitHub Community Organization. 

- #### Name: Pratham Yadav

- #### Discord Username(if exists): PSY VENOM

- #### Additional Context:

**Comment by cmulay** [comment]
## Invitation sent for the GitHub Organisation. 
### Welcome to the community 🎉
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/PHP-DC/people
