### ISSUE TITLE
Request to join organisation

### ISSUE THREAD

**Issue by Sanil711** [PHP-DC/support#6]
Please invite me to the GitHub Community Organization. 

- #### Name: Sanil Jadhav

- #### Discord Username(if exists): Cosmo_Sentinel#7794

- #### Additional Context:

**Comment by cmulay** [comment]
## Invitation sent for the GitHub Organisation. 
### Welcome to the community 🎉
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/PHP-DC/people
