### ISSUE TITLE
Add me

### ISSUE THREAD

**Issue by raj1828** [PHP-DC/support#9]
Please invite me to the GitHub Community Organization. 

- #### Name: Raj Mhatre

- #### Discord Username(if exists): raj_1828

- #### Additional Context:

**Comment by Davekibh** [comment]
I have sent you the invitation in your mail.

**Comment by cmulay** [comment]
@raj1828 Please fill out the information that is required and mandatory in order to join the [organization](https://github.com/PHP-DC)

**Comment by raj1828** [comment]
Done bro @cmulay

**Comment by Davekibh** [comment]
Cool!

**Comment by cmulay** [comment]
### Welcome to the community 🎉
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/PHP-DC/people
